# Generated by Django 5.2.3 on 2026-01-12 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='To_Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='статус')),
                ('name_user', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('address_nova_poshta', models.CharField(blank=True, max_length=100, null=True)),
                ('city_nova_poshta', models.CharField(blank=True, max_length=100, null=True)),
                ('region_nova_poshta', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_nova_poshta', models.CharField(blank=True, max_length=100, null=True)),
                ('address_ukr_poshta', models.CharField(blank=True, max_length=100, null=True)),
                ('city_ukr_poshta', models.CharField(blank=True, max_length=100, null=True)),
                ('region_ukr_poshta', models.CharField(blank=True, max_length=100, null=True)),
                ('inbex_ukr_poshta', models.CharField(blank=True, max_length=100, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна ціна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=250, null=True)),
                ('for_dad', models.BooleanField(default=True, verbose_name='для тата')),
                ('for_mom', models.BooleanField(default=True, verbose_name='для мами')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступний для продажу')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Save_user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('address_nova_poshta', models.CharField(blank=True, max_length=100, null=True)),
                ('city_nova_poshta', models.CharField(blank=True, max_length=100, null=True)),
                ('region_nova_poshta', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_nova_poshta', models.CharField(blank=True, max_length=100, null=True)),
                ('address_ukr_poshta', models.CharField(blank=True, max_length=100, null=True)),
                ('city_ukr_poshta', models.CharField(blank=True, max_length=100, null=True)),
                ('region_ukr_poshta', models.CharField(blank=True, max_length=100, null=True)),
                ('inbex_ukr_poshta', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_user_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='To_Buy_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.CharField(blank=True, max_length=250, null=True)),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Кількість товару')),
                ('status', models.BooleanField(default=True, verbose_name='статус')),
                ('name_user', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('address_nova_poshta', models.CharField(blank=True, max_length=100, null=True)),
                ('city_nova_poshta', models.CharField(blank=True, max_length=100, null=True)),
                ('region_nova_poshta', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_nova_poshta', models.CharField(blank=True, max_length=100, null=True)),
                ('address_ukr_poshta', models.CharField(blank=True, max_length=100, null=True)),
                ('city_ukr_poshta', models.CharField(blank=True, max_length=100, null=True)),
                ('region_ukr_poshta', models.CharField(blank=True, max_length=100, null=True)),
                ('inbex_ukr_poshta', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('data_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_buy_products', to='main.save_user_data')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_buy_products', to='main.product')),
                ('to_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_buy_products', to='main.to_buy')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_buy_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
