# Generated by Django 5.2.3 on 2026-01-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_save_user_data_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_buy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='to_buy',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Загальна ціна'),
        ),
    ]
